[tool.poetry]
authors = ["Free Law Project <info@free.law>"]
classifiers = [
  # "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Big Cases Bot 2"
keywords = ["legal", "courts"]
license = "BSD-2-Clause"
maintainers = ["Free Law Project <info@free.law>"]
name = "Big Cases Bot 2"
readme = "README.md"
repository = "https://github.com/freelawproject/bigcases2"
version = "0.0.1"

[tool.poetry.urls]
"Organisation Homepage" = "https://free.law/"

[tool.poetry.dependencies]
python = "^3.11"
art = "^5.8"
requests = "^2.28.2"
python-dotenv = "^0.21.1"
"Mastodon.py" = {extras = ["cryptography"], version = "^1.8.0"}
cryptography = "^39.0.0"
http-ece = "^1.1.0"
psycopg2-binary = "^2.9.5"
ansicolors = "^1.1.8"
judge-pics = "^2.0.3"
prettytable = "^3.6.0"
courts-db = "^0.10.17"
django = "^4.1.5"
djangorestframework = "^3.14.0"
django-environ = "^0.9.0"
types-requests = "^2.28.11.8"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
isort = "^5.11.4"
mypy = "^0.991"
pylint = "^2.15.10"
wheel = "^0.38.4"
pre-commit = "^3.0.1"
flynt = "^0.77"

[tool.black]
include = '''.*\.pyi?$'''
exclude = '''
(
      \.eggs
    | .*\.egg-info
    | .*migrations.*
    | \.mypy_cache
    | __pycache__
    | \.venv
)
'''
line-length = 79


[tool.isort]
profile = "black"
line_length = 79

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "79"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
bigcases2 = "bigcases2.cli:cli"
